# Generated by Django 2.2.2 on 2019-06-28 03:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoastRoastModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boast', models.CharField(max_length=280)),
                ('roast', models.CharField(max_length=280)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('downvotes', models.ManyToManyField(blank=True, related_name='down', to='ghostpostbackend.BoastRoastModel')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='up', to='ghostpostbackend.BoastRoastModel')),
            ],
        ),
    ]
