# Generated by Django 2.2.2 on 2019-06-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpostbackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boastroastmodel',
            name='boast',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='boastroastmodel',
            name='roast',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
