# Generated by Django 2.2.2 on 2019-06-28 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpostbackend', '0002_auto_20190628_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boastroastmodel',
            name='date',
        ),
    ]
