# Generated by Django 2.2.2 on 2019-06-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpostbackend', '0003_remove_boastroastmodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boastroastmodel',
            name='downvotes',
        ),
        migrations.AddField(
            model_name='boastroastmodel',
            name='downvotes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.RemoveField(
            model_name='boastroastmodel',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='boastroastmodel',
            name='upvotes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
