# Generated by Django 2.2.2 on 2019-06-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpostbackend', '0004_auto_20190628_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boastroastmodel',
            name='downvotes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='boastroastmodel',
            name='upvotes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
