# Generated by Django 2.2.2 on 2019-06-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpostbackend', '0005_auto_20190628_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boastroastmodel',
            name='boast',
        ),
        migrations.RemoveField(
            model_name='boastroastmodel',
            name='roast',
        ),
        migrations.AddField(
            model_name='boastroastmodel',
            name='post',
            field=models.CharField(choices=[('B', 'boast'), ('R', 'roast')], default='Write a boast or roast', max_length=280),
        ),
    ]
