# Generated by Django 2.2.2 on 2019-06-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpostbackend', '0006_auto_20190628_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastroastmodel',
            name='choice',
            field=models.CharField(choices=[('B', 'Boast'), ('R', 'Roast')], default=False, max_length=280),
        ),
        migrations.AlterField(
            model_name='boastroastmodel',
            name='post',
            field=models.CharField(default='Write a boast or roast', max_length=280),
        ),
    ]
