# Generated by Django 2.2.2 on 2019-06-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpostbackend', '0007_auto_20190628_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boastroastmodel',
            name='choice',
            field=models.CharField(choices=[('B', 'Boast'), ('R', 'Roast')], default='R', max_length=280),
        ),
    ]
