# Generated by Django 2.2.2 on 2019-06-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpostbackend', '0008_auto_20190629_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boastroastmodel',
            name='choice',
            field=models.CharField(choices=[('B', 'Boast'), ('R', 'Roast')], default='Boast', max_length=280),
        ),
    ]
