# Generated by Django 2.2.2 on 2019-06-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpostbackend', '0010_auto_20190629_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boastroastmodel',
            name='choice',
            field=models.CharField(choices=[('B', 'Boast'), ('R', 'Roast')], default='B', max_length=280),
        ),
    ]
